package com.zidir.medcom.domain;

import static com.zidir.medcom.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class NotificationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationAllPropertiesEquals(Notification expected, Notification actual) {
        assertNotificationAutoGeneratedPropertiesEquals(expected, actual);
        assertNotificationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationAllUpdatablePropertiesEquals(Notification expected, Notification actual) {
        assertNotificationUpdatableFieldsEquals(expected, actual);
        assertNotificationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationAutoGeneratedPropertiesEquals(Notification expected, Notification actual) {
        assertThat(actual)
            .as("Verify Notification auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationUpdatableFieldsEquals(Notification expected, Notification actual) {
        assertThat(actual)
            .as("Verify Notification relevant properties")
            .satisfies(a -> assertThat(a.getNotificationType()).as("check notificationType").isEqualTo(expected.getNotificationType()))
            .satisfies(a -> assertThat(a.getMessage()).as("check message").isEqualTo(expected.getMessage()))
            .satisfies(a ->
                assertThat(a.getReadAt()).as("check readAt").usingComparator(zonedDataTimeSameInstant).isEqualTo(expected.getReadAt())
            )
            .satisfies(a -> assertThat(a.getSent()).as("check sent").isEqualTo(expected.getSent()))
            .satisfies(a ->
                assertThat(a.getSentAt()).as("check sentAt").usingComparator(zonedDataTimeSameInstant).isEqualTo(expected.getSentAt())
            )
            .satisfies(a -> assertThat(a.getDelivered()).as("check delivered").isEqualTo(expected.getDelivered()))
            .satisfies(a ->
                assertThat(a.getDeliveredAt())
                    .as("check deliveredAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getDeliveredAt())
            )
            .satisfies(a -> assertThat(a.getFailed()).as("check failed").isEqualTo(expected.getFailed()))
            .satisfies(a ->
                assertThat(a.getFailedAt()).as("check failedAt").usingComparator(zonedDataTimeSameInstant).isEqualTo(expected.getFailedAt())
            )
            .satisfies(a -> assertThat(a.getFailureReason()).as("check failureReason").isEqualTo(expected.getFailureReason()))
            .satisfies(a -> assertThat(a.getExternalMessageId()).as("check externalMessageId").isEqualTo(expected.getExternalMessageId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationUpdatableRelationshipsEquals(Notification expected, Notification actual) {
        assertThat(actual)
            .as("Verify Notification relationships")
            .satisfies(a -> assertThat(a.getPharmacy()).as("check pharmacy").isEqualTo(expected.getPharmacy()))
            .satisfies(a -> assertThat(a.getWatchListItem()).as("check watchListItem").isEqualTo(expected.getWatchListItem()));
    }
}
