package com.zidir.medcom.domain;

import static com.zidir.medcom.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class WatchListItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWatchListItemAllPropertiesEquals(WatchListItem expected, WatchListItem actual) {
        assertWatchListItemAutoGeneratedPropertiesEquals(expected, actual);
        assertWatchListItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWatchListItemAllUpdatablePropertiesEquals(WatchListItem expected, WatchListItem actual) {
        assertWatchListItemUpdatableFieldsEquals(expected, actual);
        assertWatchListItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWatchListItemAutoGeneratedPropertiesEquals(WatchListItem expected, WatchListItem actual) {
        assertThat(actual)
            .as("Verify WatchListItem auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWatchListItemUpdatableFieldsEquals(WatchListItem expected, WatchListItem actual) {
        assertThat(actual)
            .as("Verify WatchListItem relevant properties")
            .satisfies(a -> assertThat(a.getLastAvailability()).as("check lastAvailability").isEqualTo(expected.getLastAvailability()))
            .satisfies(a ->
                assertThat(a.getLastAvailabilityTime())
                    .as("check lastAvailabilityTime")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getLastAvailabilityTime())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWatchListItemUpdatableRelationshipsEquals(WatchListItem expected, WatchListItem actual) {
        assertThat(actual)
            .as("Verify WatchListItem relationships")
            .satisfies(a -> assertThat(a.getProduct()).as("check product").isEqualTo(expected.getProduct()))
            .satisfies(a -> assertThat(a.getPharmacy()).as("check pharmacy").isEqualTo(expected.getPharmacy()));
    }
}
